name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2.2.4
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'AcclaimedAP'
        reponame: 'cv2023'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
